codegen: Mark just 1.25.1 as broken
As of 2024-03-10 07:03 UTC, this release only contains a x86_64 Linux binaries.

```
Error: platform list in base manifest for just contains x86_64_macos, but latest release (1.25.1) doesn't contain it; consider marking 1.25.1 as broken by adding 'broken' field to base manifest
```

https://github.com/casey/just/actions/runs/8217664170/job/22473612069