codegen: Mark cargo-rdme 1.4.3 as broken
As of 2024-02-13 01:30 UTC, this release only contains Windows binary.

```
Error: platform list in base manifest for cargo-rdme contains x86_64_linux_musl, but latest release (1.4.3) doesn't contain it
```