ci: Temporarily disable broken archlinux test
```
  :: Synchronizing package databases...
   core downloading...
   extra downloading...
  resolving dependencies...
  looking for conflicting packages...

  Package (9)           New Version                  Net Change  Download Size

  core/db5.3            5.3.28-7                       6.48 MiB       1.26 MiB
  core/libgcc           15.2.1+r604+g0b99615a8aef-1    0.17 MiB       0.08 MiB
  core/libstdc++        15.2.1+r604+g0b99615a8aef-1    2.57 MiB       0.75 MiB
  core/perl             5.42.0-1                      69.88 MiB      20.40 MiB
  extra/perl-error      0.17030-3                      0.04 MiB       0.02 MiB
  extra/perl-mailtools  2.22-3                         0.10 MiB       0.06 MiB
  extra/perl-timedate   2.33-9                         0.08 MiB       0.03 MiB
  extra/zlib-ng         2.3.3-1                        0.28 MiB       0.11 MiB
  extra/git             2.53.0-1                      29.72 MiB       6.83 MiB

  Total Download Size:    29.53 MiB
  Total Installed Size:  109.31 MiB

  :: Proceed with installation? [Y/n]
  :: Retrieving packages...
   perl-5.42.0-1-x86_64 downloading...
   git-2.53.0-1-x86_64 downloading...
   db5.3-5.3.28-7-x86_64 downloading...
   libstdc++-15.2.1+r604+g0b99615a8aef-1-x86_64 downloading...
   zlib-ng-2.3.3-1-x86_64 downloading...
   libgcc-15.2.1+r604+g0b99615a8aef-1-x86_64 downloading...
   perl-mailtools-2.22-3-any downloading...
   perl-timedate-2.33-9-any downloading...
   perl-error-0.17030-3-any downloading...
  checking keyring...
  checking package integrity...
  loading package files...
  checking for file conflicts...
  error: failed to commit transaction (conflicting files)
  libgcc: /usr/lib/libgcc_s.so exists in filesystem (owned by gcc-libs)
  libgcc: /usr/lib/libgcc_s.so.1 exists in filesystem (owned by gcc-libs)
  libgcc: /usr/share/licenses/gcc-libs/RUNTIME.LIBRARY.EXCEPTION exists in filesystem (owned by gcc-libs)
  libstdc++: /usr/lib/libstdc++.so exists in filesystem (owned by gcc-libs)
  libstdc++: /usr/lib/libstdc++.so.6 exists in filesystem (owned by gcc-libs)
  libstdc++: /usr/lib/libstdc++.so.6.0.34 exists in filesystem (owned by gcc-libs)
  Errors occurred, no packages were upgraded.
```