Mark cargo-dinghy 0.7.0 as broken
As of 2024-04-10 01:52 UTC, this release only contains a x86_64 Linux binaries.

```
Error: platform list in base manifest for cargo-dinghy contains x86_64_macos, but latest release (0.7.0) doesn't contain it; consider marking 0.7.0 as broken by adding 'broken' field to base manifest
```

https://github.com/sonos/dinghy/actions/runs/8618768640/job/23621914742#step:4:257