Revert "Fix version output"
This reverts commit a4e2a0d24a04d06db8f228798c3671bd79b37846.

```
+ cargo-machete machete --version
Analyzing dependencies of crates in machete,--version...
Done!
Error: Errors when walking over directories:
IO error for operation on machete: No such file or directory (os error 2)
IO error for operation on --version: No such file or directory (os error 2)
```