codegen: Mark just 1.25.0 as broken
As of 2024-03-08 01:42 UTC, this release only contains a few Linux binaries.

```
Error: platform list in base manifest for just contains x86_64_macos, but latest release (1.25.0) doesn't contain it; consider marking 1.25.0 as broken by adding 'broken' field to base manifest
```

https://github.com/casey/just/actions/runs/8196561542